# Generated by Django 5.2.5 on 2025-08-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='birt_date',
            new_name='birth_date',
        ),
    ]
